# Generated by Django 5.1.6 on 2025-04-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='course_id')),
                ('course_name', models.CharField(max_length=30)),
                ('duration', models.IntegerField(help_text='Duration in month')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.IntegerField(verbose_name='Enrollment Number')),
                ('admission_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial')], default='PENDING', max_length=10, verbose_name='Payment Status')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.course', verbose_name='course_name')),
            ],
        ),
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=50)),
                ('member_password', models.CharField(max_length=10)),
                ('member_phone', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('photo', models.FileField(null=True, upload_to='static/images/student_photos/')),
                ('marks', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('1', 'Cash'), ('2', 'UPI'), ('3', 'Bank Transfer'), ('4', 'Cheque'), ('5', 'Credit Card'), ('6', 'Debit Card'), ('7', 'Net Banking')], default='1', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_transfer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('debit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('net_banking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='myapp.course')),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='myapp.enrollment')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.student', verbose_name='name'),
        ),
    ]
