# Generated by Django 5.1.6 on 2025-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='student_name',
            new_name='student',
        ),
    ]
