# Generated by Django 5.1.6 on 2025-04-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='student',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Idcard',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
