# Generated by Django 5.1.6 on 2025-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_number',
            field=models.CharField(max_length=30, verbose_name='Enrollment Number'),
        ),
    ]
